version: '2.1'
services:
#...
  localstack:
    image: localstack/localstack
    ports:
      - "4574:4574"
      - "8080:8080"
    environment:
      - SERVICES=lambda
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
#      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
#      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /tmp/localstack:/tmp/localstack

# aws --endpoint-url=http://localhost:4574 lambda create-function --region 'us-west-1' --function-name lambda-demo --runtime python3.7 --role arn:aws:iam::123456:role/irrelevant --handler lambda_function.lambda_handler --zip-file fileb://lambda.zip

# aws --endpoint-url=http://localhost:4574 lambda invoke --function-name lambda-demo --invocation-type Event output.txt