version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4572:4572"
      - "8080:8080"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY